from pages.ondemand.web.booking.pickup_time_modal.pickup_time_modal import PickupTimeModal
from utilities import Component, Selector, Selectors, WebElement


class ServiceSelectModal(Component):
    """Objects and methods for the Service Select Modal component."""

    ROOT_LOCATOR: Selector = Selectors.data_id('service-select-modal-container')
    _main_menu_link: Selector = Selectors.data_id('modal-main-menu-link')

    @property
    def main_menu_link(self) -> WebElement:
        return self.container.find_element(*self._main_menu_link)

    def select_service_by_id(self, service_id: int) -> object:
        """Select a service based on a unique service ID.

        :param service_id: The unique service ID generated by a Service Factory.
        """
        service = self.driver.find_element(*Selectors.data_id(str(service_id)))
        service.mouse_over()

        service.click()

        return PickupTimeModal(self).wait_for_component_to_be_present()
